### ISSUE TITLE
akmods cache layer

### ISSUE THREAD

**Issue by m2Giles** [0ranki/silverblue-zfs#2]
As a heads up, ublue already builds the zfs modules every day for the coreos kernel.

https://github.com/ublue-os/akmods/pkgs/container/akmods/236997469?tag=coreos-40

**Comment by 0ranki** [comment]
Thanks! I did try the Ucore approach first. When I started this, SB/Ublue and CoreOS/Ucore were on different release schedules, so the module's weren't compatible with SB kernel most of the time.

Has there been a change to this? The build runs daily against the `ublue-os:main` image's kernel

**Comment by m2Giles** [comment]
Yeah this week we started building against the coreOS kernel for F40 and the matched kernel for F39.

We are not building against latest due to how fast the kernel moves often releasing before zfs is compatible.

**Comment by 0ranki** [comment]
Yup, I understood it correctly then.

I actually thought about basing this image against a `stable` weekly image of base Universal Blue (if such exists) when the CoreOS-style images where announced, but haven't got around to it yet.

I'll follow Bluefin to see how you do it, but for the current system using the caching layer probably won't work. The weekly cadence would suit my own needs better, actually. Thanks for the heads up!
